name: C/C++ CI

on:
  push:
    branches:
    - "master"
    - "*-draft"
  pull_request:
    branches:
    - "master"
    - "*-draft"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: ConorMacBride/install-package@v1
      with:
        apt: libsfml-dev libsdl2-dev clang-tidy clang clang-format
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: make check
      run: make check
