name: C/C++ CI

on: [ "pull_request" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: ConorMacBride/install-package@v1
      with:
        apt: libsfml-dev libsdl2-dev clang-tidy clang clang-format
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: make check
      run: make check
    - name: Add commit status
      uses: octodemo-resources/github-commit-status@v1
        with:
          context: build_results
          state: success
          description: Build completed sucessfully
          target_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
